spring:
  application:
    name: store
  datasource:
    url: jdbc:h2:mem:store-api
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:config/liquibase/changelog/db.changelog-master.yml
    enabled: true
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

application:
  jwt:
    secret: MGRhN2RjNmE4NzBhNzdlNjZmYzczMTJjNDcxODAzMjllNjM0ZWYwYjVlZWJlZGE5NjUwNTVjNTc5NTQ5OWZhNmM2N2E3ODU5MjgxOGY1ZGY1ZmRlODkzY2QyMDQyOTM1NDI4M2Y2YTNhOTUzZTk0N2Y5NDVkZjU3NzRkZWRjMWE=
    token-validity-in-seconds: 86400
  security:
    content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; frame-ancestors 'self';"