databaseChangeLog:
  - changeSet:
      id: 00000000000000
      author: gapatmej
      changes:
        - createSequence:
            sequenceName: sequence_generator
            startValue: 1050
            incrementBy: 50

  - changeSet:
      id: 00000000000001
      author: gapatmej
      changes:
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: login
                  type: varchar(50)
                  constraints:
                    unique: true
                    nullable: false
                    uniqueConstraintName: ux_user_login
              - column:
                  name: password_hash
                  type: varchar(60)
              - column:
                  name: first_name
                  type: varchar(50)
              - column:
                  name: last_name
                  type: varchar(50)
              - column:
                  name: email
                  type: varchar(191)
                  constraints:
                    unique: true
                    nullable: true
                    uniqueConstraintName: ux_user_email
              - column:
                  name: activated
                  type: boolean
                  defaultValueBoolean: false
                  constraints:
                    nullable: false
              - column:
                  name: created_by
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: timestamp
              - column:
                  name: last_modified_by
                  type: varchar(50)
              - column:
                  name: last_modified_date
                  type: timestamp

        - createTable:
            tableName: authorities
            columns:
              - column:
                  name: name
                  type: varchar(50)
                  constraints:
                    primaryKey: true
                    nullable: false

        - createTable:
            tableName: user_authority
            columns:
              - column:
                  name: user_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: authority_name
                  type: varchar(50)
                  constraints:
                    nullable: false

        - addPrimaryKey:
            columnNames: user_id, authority_name
            tableName: user_authority

        - addForeignKeyConstraint:
            baseColumnNames: authority_name
            baseTableName: user_authority
            constraintName: fk_authority_name
            referencedColumnNames: name
            referencedTableName: authorities

        - addForeignKeyConstraint:
            baseColumnNames: user_id
            baseTableName: user_authority
            constraintName: fk_user_id
            referencedColumnNames: id
            referencedTableName: users

        - addNotNullConstraint:
            columnName: password_hash
            columnDataType: varchar(60)
            tableName: users

        - loadData:
            file: config/liquibase/data/users.csv
            separator: ";"
            tableName: users
            usePreparedStatements: true
            columns:
              - column:
                  name: id
                  type: numeric
              - column:
                  name: activated
                  type: boolean
              - column:
                  name: created_date
                  type: timestamp

        - dropDefaultValue:
            tableName: users
            columnName: created_date
            columnDataType: ${datetimeType}

        - loadData:
            file: config/liquibase/data/authorities.csv
            separator: ";"
            tableName: authorities
            usePreparedStatements: true
            columns:
              - column:
                  name: name
                  type: string

        - loadData:
            file: config/liquibase/data/user_authority.csv
            separator: ";"
            tableName: user_authority
            usePreparedStatements: true
            columns:
              - column:
                  name: user_id
                  type: numeric